// BNG Remodel standard contract boilerplate.
// This is the exact contract language Brittney attaches to every estimate.
// Stored here so it can be included in every proposal/contract PDF.

export const BNG_CONTRACT_TEXT = `BNG Remodel General EContract

An individual aged 18+ must be present when BNG Remodel's installation team arrives. If the installation team arrives at the scheduled time and is unable to access the work area, a $250 rescheduling fee will apply. The $250 rescheduling fee will be charged to the client for every day that work cannot be done due to not having access to the residence and/or commercial space.

The client is responsible for providing electricity during the project and for ensuring that adults, children and pets do not interfere with the project's progress. BNG Remodel will not remove or disconnect any plumbing or electrical fixtures, including appliances and outlets (unless specifically stated in the estimate).

This contract does not include mold abatement or asbestos removal. If mold or asbestos are discovered at any point during the project, the installation team will cease work until the client addresses the issue to BNG Remodel's satisfaction. If the commercial property or residential home has galvanized steel piping, we are not responsible for replacing water lines unless specifically stated in the estimate. Otherwise, replacing any supply lines will result in an additional cost, which will be a separate quote. Unless specifically included in this contract, electrical work shall not involve a change to any existing service panel. This contract does not include changes to existing wiring in areas undisturbed by alterations. All existing electrical wiring systems are presumed to be, and owner represents them to be, adequate to carry the load imposed by existing work. Any work necessary to correct those conditions will result in an additional cost, which will be a separate quote.

BNG Remodel shall not be held liable for damage to driveways, walks, lawns, shrubs, or other vegetation by movement of vehicles, workers, equipment, materials, or debris. BNG Remodel is not responsible for any existing illegal conditions. BNG Remodel is not responsible for any existing old, fragile, or poor conditions, including but not limited to rotted or corroded material. BNG Remodel is not responsible for any "pre-existing material" whatsoever. "Pre-existing material" consists of ALL material that is in the residence or commercial space, outside of the new material that BNG Remodel is installing. "Pre-existing material" includes, but not limited to, flooring, plumbing fixtures, lighting fixtures, sheetrock (walls), paint, countertops, cabinetry, etc. BNG Remodel is not responsible for any unusual or abnormal concrete footings, foundations, retaining walls, or piers required or any unusual depth requirements, such as, but not limited to conditions caused by poor soil, lack of compaction, hillside, or other slope conditions. BNG Remodel is not obligated to correct those conditions. All additional work needed to correct those conditions will be an additional cost on a separate quote. BNG Remodel is not responsible for matching previous tile floor or other flooring options. It is not reasonable to match new flooring with older flooring. A selection for the flooring will be made and confirmed with customer before install. BNG Remodel is not responsible for matching new siding with pre-existing siding. Manufacturers discontinue siding colors and designs often; as well the exterior weather conditions cause siding to fade and/or change color due to other weather variances. We do the best we can, but it is not exact due to manufacturer release of certain products and discontinuation of other products. If pre-existing material does not match new material in circumstances, a change order will be sent to install all new flooring, tile and/or siding in that specific space. BNG Remodel will communicate all options to customer before any final decisions are made.

BNG Remodel offers a 1 year guarantee (warranty) on installation. This guarantee does not cover anything not related to installation. The warranty does not cover ordinary wear and tear, abuse, neglect, or acts of God. BNG Remodel does not guarantee any materials, equipment, assemblies, or units that have been purchased or will be purchased as part of the work covered in this contract. All of these items are subject to manufacturers' or processors' guarantees or warranties.

Customer provided material must be on site before the start of the project. If it is not and the schedule of the project is affected as to which the employees, subcontractors, and/or vendors cannot complete their respective portion of the project when they are scheduled to do so, there may be an additional charge for project delay per day in the amount of $500/per day. All decisions regarding project delay charges will be made by Brittney Reader of BNG Remodel. Customer design changes and/or customer related delays will cause the customer to be solely responsible for any additional costs for dumpsters that need to be ordered and dropped.

For payment, we accept cash, cashiers check, wire transfer and credit/debit card. All wire transfer payments are subject to a $35 wire transfer fee per transaction. All debit and credit card payments are subject to a 3.5% processing fee. An initial deposit equal to 30% of the total project cost is due for the project to be scheduled. Once the project reaches the halfway point, an additional 40% of the total project cost is due. BNG Remodel shall have the right to stop work and keep the project idle if payments are not made to BNG Remodel when due. If work is stopped for any reason, the owner of the property must provide for protection of all material on the premises and shall be responsible for any damage, warpage, racking or loss of that material. The remaining balance is due immediately upon project completion. Any payment past that date will be subject to a $100 late fee per day. Interest will be added to and payable on all overdue amounts at 18% per year, or the maximum percentage allowed under applicable laws, whichever is less. The customer shall reimburse BNG Remodel for all costs of collection, including reasonable attorney's fees.

This contract shall be the sole agreement between BNG Remodel and the client. No other agreements, arrangements or promises are valid.

BNG Remodel's liability shall in all cases be limited to the terms of our liability insurance, and shall in no case extend beyond damages directly caused by our work.

BNG Remodel is not responsible for dust that may be associated with demolition or installation. Dust is going to occur with any demo or install; so it is the responsibility of the customer for any cleanup. BNG Remodel calls owner's attention to, and owner acknowledges the limitations of BNG Remodel's ability to completely remove certain remnants of debris, such as dust from drywall, plaster, or other materials due to the nature of the work. BNG Remodel is not responsible for any damage or injury caused by dust or similar debris that may remain in the home and/or ventilation due to the inability to remove completely and/or circulation of air.

Minor damage to walls and baseboards may occur during the project. If drywall repair or painting needs to be done, there will be an additional charge. Items moved by BNG Remodel will be with the customer's permission and relieves BNG Remodel of any liability whatsoever. BNG Remodel guarantees no specific start or completion date. There is always the potential that work could take longer than quoted due to unforeseen circumstances. Our goal is to always make the customer happy and we strive to finish work as promptly as possible. BNG Remodel shall in no event be held liable for delay, cancellation or damage due to unforeseen circumstances, such as, but not limited to, natural disaster.

BNG Remodel does not offer any refunds or credits on installation itself. Any returns or exchanges on material will be up to Brittney Reader of BNG Remodel.

Owner/renter(s) of the property understand and agree not to engage any side arrangement or separate contracts with any of BNG Remodel's employees, vendors or subcontractors performing work on this job, for a period of at least one year following the completion of this job, except as provided by agreement with BNG Remodel pursuant to the terms of this contract. Any such agreement must be approved by BNG Remodel prior to such agreement or contract in writing. If a separate agreement is made between the owner/renter(s) and others, the owner/renter(s) may not hold BNG Remodel responsible for the quality of workmanship and materials utilized by these persons, or their time schedule or job cleanliness.

Owner expressly authorizes Brittney Reader of BNG Remodel to take and distribute "before and after" photos and videos (as well as progress photos and videos) for training and/or advertising and marketing purposes.

During the term of BNG Remodel's work on the project, and thereafter, owner shall not make disparaging remarks, or any remarks that could reasonably be construed as disparaging, regarding BNG Remodel, its employees, subcontractors, vendors, representatives, or agents. For purposes of this section, "disparage" shall mean any negative statements, reviews, comments, or feedback, whether written or oral, about BNG Remodel.

If at any time during work, and for one year following completion, if Owner believes there is a defect in the work, the owner must first give BNG Remodel an opportunity to repair before seeking a third party for repairs. If owner refuses to allow BNG Remodel the first opportunity and thirty days to repair, BNG Remodel will not be liable for any such damage and/or repair.`;

// HTML version of the contract for PDF rendering.
// Each paragraph becomes its own <p> tag for clean formatting.
export const BNG_CONTRACT_HTML = BNG_CONTRACT_TEXT
  .split('\n\n')
  .map((paragraph) => {
    const trimmed = paragraph.trim();
    if (!trimmed) return '';
    if (trimmed === 'BNG Remodel General EContract') {
      return `<h2 style="font-size:20px;font-weight:800;color:#1E3A8A;margin-bottom:16px;text-align:center;">BNG Remodel General EContract</h2>`;
    }
    return `<p style="font-size:12px;color:#1E293B;line-height:1.7;margin-bottom:14px;text-align:justify;">${trimmed}</p>`;
  })
  .join('\n');
